name: damask-esolang
version: 0.0.0
license: MIT
author: bnspalding
github: bnspalding/damask-esolang
stability: experimental
synopsis: a poetic esolang interpreter
description: >-
  damask-esolang interprets punctuation in a source-poem as a sequence of 
  encoded transformations to generate a second poem woven from the elements of
  the source.

dependencies:
  - base >= 4.9 && < 5
  - text
  - parsec

library:
  source-dirs: src

executables:
  damask:
    main: Main.hs
    source-dirs: app
    dependencies:
      - damask-esolang

tests:
  damask-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - damask-esolang
      - hspec

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

